FROM ubuntu:24.10 AS base

RUN apt update && apt install -y default-jre default-jdk git unzip wget

FROM base AS deps
WORKDIR /build

# Only to version the artifact properly
COPY .git .

COPY gradlew .
COPY build.gradle .
COPY gradle ./gradle
COPY gradle.properties .
COPY settings.gradle .
COPY buildSrc ./buildSrc
COPY besu-plugins/linea-sequencer/gradle ./besu-plugins/linea-sequencer/gradle
COPY besu-plugins/linea-sequencer/build.gradle ./besu-plugins/linea-sequencer/build.gradle
COPY besu-plugins/linea-sequencer/sequencer/build.gradle ./besu-plugins/linea-sequencer/sequencer/build.gradle

RUN ./gradlew besu-plugins:linea-sequencer:sequencer:artifacts --no-daemon --build-cache

# Builds the linea-sequencer plugin
FROM deps AS build
WORKDIR /build

COPY besu-plugins/linea-sequencer/sequencer/src ./besu-plugins/linea-sequencer/sequencer/src
RUN ./gradlew besu-plugins:linea-sequencer:sequencer:artifacts --no-daemon --build-cache

FROM base AS injection
WORKDIR /app
COPY linea-besu-package ./linea-besu-package
RUN cd linea-besu-package && ./scripts/assemble-packages.sh && rm ./tmp/besu/plugins/linea-sequencer-*.jar

COPY --from=build /build/besu-plugins/linea-sequencer/sequencer/build/distributions/linea-sequencer-*.zip ./linea-besu-package

RUN unzip ./linea-besu-package/linea-sequencer-*.zip linea-sequencer-*.jar -d linea-besu-package/tmp/besu/plugins/

FROM ubuntu:24.04 AS release
ARG VERSION="dev"
ENV NO_PROXY_CACHE="-o Acquire::BrokenProxy=true -o Acquire::http::No-Cache=true -o Acquire::http::Pipeline-Depth=0"

# Update and install dependencies without using any cache
RUN apt-get update $NO_PROXY_CACHE  && \
  # $NO_PROXY_CACHE must not be used here or otherwise will trigger a hadolint error
  apt-get -o Acquire::BrokenProxy=true -o Acquire::http::No-Cache=true -o Acquire::http::Pipeline-Depth=0 \
    --no-install-recommends -q --assume-yes install openjdk-21-jre-headless=21* libjemalloc-dev=5.* adduser=3*  && \
  # Clean apt cache
  apt-get clean  && \
  rm -rf /var/cache/apt/archives/* /var/cache/apt/archives/partial/*  && \
  rm -rf /var/lib/apt/lists/*  && \
  # Starting from version 23.10, Ubuntu comes with an "ubuntu" user with uid 1000. We need 1000 for besu.
  userdel ubuntu 2>/dev/null || true && rm -rf /home/ubuntu  && \
  # Ensure we use a stable UID for besu, as file permissions are tied to UIDs.
  adduser --uid 1000 --disabled-password --gecos "" --home /opt/besu besu  && \
  chown besu:besu /opt/besu  && \
  chmod 0755 /opt/besu  && \
  # Create /data folder and set permissions
  mkdir /data  && \
  chown besu:besu /data  && \
  chmod 0755 /data

USER besu
WORKDIR /opt/besu

COPY --from=injection --chown=besu:besu /app/linea-besu-package/tmp/besu /opt/besu/
RUN sed -i '/^CLASSPATH/c\CLASSPATH=/opt/besu/lib/\*\:/opt/besu/plugins/\*' /opt/besu/bin/besu
RUN sed -i '/^CLASSPATH/c\CLASSPATH=/opt/besu/lib/\*\:/opt/besu/plugins/\*' /opt/besu/bin/besu.bat
RUN sed -i '/^CLASSPATH/c\CLASSPATH=/opt/besu/lib/\*\:/opt/besu/plugins/\*' /opt/besu/bin/besu-untuned
RUN sed -i '/^CLASSPATH/c\CLASSPATH=/opt/besu/lib/\*\:/opt/besu/plugins/\*' /opt/besu/bin/besu-untuned.bat

EXPOSE 8545 8546 8547 8550 8551 30303

# defaults for host interfaces
ENV BESU_RPC_HTTP_HOST 0.0.0.0
ENV BESU_RPC_WS_HOST 0.0.0.0
ENV BESU_GRAPHQL_HTTP_HOST 0.0.0.0
ENV BESU_PID_PATH "/tmp/pid"

ENV OTEL_RESOURCE_ATTRIBUTES="service.name=besu,service.version=$VERSION"

ENV OLDPATH="${PATH}"
ENV PATH="/opt/besu/bin:${OLDPATH}"

ENTRYPOINT ["besu"]
HEALTHCHECK --start-period=5s --interval=5s --timeout=1s --retries=10 CMD bash -c "[ -f /tmp/pid ]"

# Build-time metadata as defined at http://label-schema.org
ARG BUILD_DATE
ARG VCS_REF
LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="Besu" \
      org.label-schema.description="Enterprise Ethereum client" \
      org.label-schema.url="https://besu.hyperledger.org/" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/hyperledger/besu.git" \
      org.label-schema.vendor="Hyperledger" \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0"
